### ISSUE TITLE
jupyterlab extension installation error:  Module not found: Error: Can't resolve 'k3d/dist/labplugin'

### ISSUE THREAD

**Issue by yambottle** [K3D-tools/K3D-jupyter#336]
Jupyterlab Version: 3.2.2

Error:
```
webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'k3d/dist/labplugin' in '/opt/conda/share/jupyter/lab/staging/build'
```

Full error stack:
```
Node v17.8.0

Yarn configuration loaded.
> /opt/conda/bin/npm pack k3d
npm notice
npm notice 📦  k3d@2.12.0
npm notice === Tarball Contents ===
npm notice 761B   .eslintrc.js
npm notice 2.0kB  Gruntfile.js
npm notice 1.2kB  HOW-TO.md
npm notice 550B   README.md
npm notice 1.9kB  development_tf.html
npm notice 1.8kB  development.html
npm notice 3.6MB  dist/index.js
npm notice 1.7kB  dist/index.js.LICENSE.txt
npm notice 6.9MB  dist/index.js.map
npm notice 3.9MB  dist/standalone.js
npm notice 2.7kB  dist/standalone.js.LICENSE.txt
npm notice 8.9MB  dist/standalone.js.map
npm notice 2.0kB  package.json
npm notice 40.8kB src/core/Core.js
npm notice 609B   src/core/lib/cameraMode.js
npm notice 463B   src/core/lib/clippingPlanesGUIProvider.js
npm notice 5.5kB  src/core/lib/colorMapLegend.js
npm notice 3.0kB  src/core/lib/detachWindow.js
npm notice 1.4kB  src/core/lib/Error.js
npm notice 783B   src/core/lib/fullscreen.js
npm notice 4.7kB  src/core/lib/headless.html
npm notice 2.2kB  src/core/lib/helpers/buffer.js
npm notice 5.9kB  src/core/lib/helpers/colorMap.js
npm notice 119B   src/core/lib/helpers/detachedWindowHtml.js
npm notice 279B   src/core/lib/helpers/diff.js
npm notice 309B   src/core/lib/helpers/fileLoader.js
npm notice 162B   src/core/lib/helpers/float16Array.js
npm notice 19.7kB src/core/lib/helpers/marchingCubesLookupTables.js
npm notice 4.5kB  src/core/lib/helpers/marchingCubesPolygonise.js
npm notice 204B   src/core/lib/helpers/math.js
npm notice 1.1kB  src/core/lib/helpers/objectValidator.js
npm notice 5.6kB  src/core/lib/helpers/planeGUI.js
npm notice 3.4kB  src/core/lib/helpers/serialize.js
npm notice 10.7kB src/core/lib/helpers/voxelMeshGenerator.js
npm notice 420B   src/core/lib/helpers/yieldingLoop.js
npm notice 2.9kB  src/core/lib/Loader.js
npm notice 992B   src/core/lib/manipulate.js
npm notice 14.5kB src/core/lib/objectsGUIprovider.js
npm notice 290B   src/core/lib/resetCamera.js
npm notice 4.0kB  src/core/lib/screenshot.js
npm notice 1.6kB  src/core/lib/snapshot_inline.txt
npm notice 1.5kB  src/core/lib/snapshot_online.txt
npm notice 1.7kB  src/core/lib/snapshot_standalone.txt
npm notice 5.4kB  src/core/lib/snapshot.js
npm notice 9.0kB  src/core/lib/timeSeries.js
npm notice 706B   src/core/lib/viewMode.js
npm notice 290B   src/development.js
npm notice 218B   src/embed.js
npm notice 816B   src/extension.js
npm notice 212B   src/index.js
npm notice 1.4kB  src/k3d.css
npm notice 23.3kB src/k3d.js
npm notice 546B   src/labplugin.js
npm notice 748B   src/lodash.js
npm notice 8.9kB  src/providers/threejs/helpers/Fn.js
npm notice 1.9kB  src/providers/threejs/helpers/Intersection.js
npm notice 5.6kB  src/providers/threejs/helpers/SSAAChunkedRender.js
npm notice 6.2kB  src/providers/threejs/helpers/Streamline.js
npm notice 954B   src/providers/threejs/helpers/THREE.CopyShader.js
npm notice 16.6kB src/providers/threejs/helpers/THREE.MeshLine.js
npm notice 32.8kB src/providers/threejs/helpers/THREE.OrbitControls.js
npm notice 11.3kB src/providers/threejs/helpers/THREE.STLLoader.js
npm notice 24.0kB src/providers/threejs/helpers/THREE.TrackballControls.js
npm notice 58.7kB src/providers/threejs/helpers/TransformControls.js
npm notice 10.9kB src/providers/threejs/helpers/Voxels.js
npm notice 7.4kB  src/providers/threejs/initializers/Camera.js
npm notice 6.2kB  src/providers/threejs/initializers/Canvas.js
npm notice 3.3kB  src/providers/threejs/initializers/Manipulate.js
npm notice 10.2kB src/providers/threejs/initializers/Renderer.js
npm notice 25.5kB src/providers/threejs/initializers/Scene.js
npm notice 486B   src/providers/threejs/initializers/Setup.js
npm notice 1.0kB  src/providers/threejs/interactions/intersectCallback.js
npm notice 7.6kB  src/providers/threejs/interactions/Voxels.js
npm notice 10.2kB src/providers/threejs/objects/Label.js
npm notice 1.3kB  src/providers/threejs/objects/Line.js
npm notice 2.8kB  src/providers/threejs/objects/LineMesh.js
npm notice 3.9kB  src/providers/threejs/objects/LineSimple.js
npm notice 5.6kB  src/providers/threejs/objects/LineThick.js
npm notice 7.1kB  src/providers/threejs/objects/MarchingCubes.js
npm notice 1.2kB  src/providers/threejs/objects/Mesh.js
npm notice 8.9kB  src/providers/threejs/objects/MeshStandard.js
npm notice 6.8kB  src/providers/threejs/objects/MeshVolume.js
npm notice 7.2kB  src/providers/threejs/objects/MIP.js
npm notice 1.3kB  src/providers/threejs/objects/Points.js
npm notice 9.1kB  src/providers/threejs/objects/PointsBillboard.js
npm notice 8.0kB  src/providers/threejs/objects/PointsMesh.js
npm notice 911B   src/providers/threejs/objects/shaders/MeshVolume.fragment.glsl
npm notice 394B   src/providers/threejs/objects/shaders/MeshVolume.vertex.glsl
npm notice 5.2kB  src/providers/threejs/objects/shaders/MIP.fragment.glsl
npm notice 788B   src/providers/threejs/objects/shaders/MIP.vertex.glsl
npm notice 1.8kB  src/providers/threejs/objects/shaders/Points.3d.fragment.glsl
npm notice 334B   src/providers/threejs/objects/shaders/Points.dot.fragment.glsl
npm notice 1.2kB  src/providers/threejs/objects/shaders/Points.dot.vertex.glsl
npm notice 520B   src/providers/threejs/objects/shaders/Points.flat.fragment.glsl
npm notice 1.3kB  src/providers/threejs/objects/shaders/Points.vertex.glsl
npm notice 2.3kB  src/providers/threejs/objects/shaders/PointsMesh.fragment.glsl
npm notice 1.8kB  src/providers/threejs/objects/shaders/PointsMesh.vertex.glsl
npm notice 549B   src/providers/threejs/objects/shaders/Texture.fragment.glsl
npm notice 304B   src/providers/threejs/objects/shaders/Texture.vertex.glsl
npm notice 9.6kB  src/providers/threejs/objects/shaders/Volume.fragment.glsl
npm notice 5.0kB  src/providers/threejs/objects/shaders/Volume.lightmap.fragment.glsl
npm notice 134B   src/providers/threejs/objects/shaders/Volume.lightmap.vertex.glsl
npm notice 788B   src/providers/threejs/objects/shaders/Volume.vertex.glsl
npm notice 2.8kB  src/providers/threejs/objects/SparseVoxels.js
npm notice 2.8kB  src/providers/threejs/objects/STL.js
npm notice 4.1kB  src/providers/threejs/objects/Surface.js
npm notice 5.5kB  src/providers/threejs/objects/Text.js
npm notice 4.6kB  src/providers/threejs/objects/Text2d.js
npm notice 887B   src/providers/threejs/objects/Texture.js
npm notice 6.8kB  src/providers/threejs/objects/TextureData.js
npm notice 3.3kB  src/providers/threejs/objects/TextureImage.js
npm notice 4.6kB  src/providers/threejs/objects/TextureText.js
npm notice 2.0kB  src/providers/threejs/objects/TorusKnot.js
npm notice 6.2kB  src/providers/threejs/objects/VectorField.js
npm notice 6.0kB  src/providers/threejs/objects/Vectors.js
npm notice 15.4kB src/providers/threejs/objects/Volume.js
npm notice 1.0kB  src/providers/threejs/objects/Voxels.js
npm notice 8.3kB  src/providers/threejs/objects/VoxelsGroup.js
npm notice 2.7kB  src/providers/threejs/provider.js
npm notice 2.1kB  src/standalone.js
npm notice 18.9kB src/transferFunctionEditor.js
npm notice 146B   src/version.js
npm notice 4.7kB  webpack.config.js
npm notice === Tarball Details ===
npm notice name:          k3d
npm notice version:       2.12.0
npm notice filename:      k3d-2.12.0.tgz
npm notice package size:  6.9 MB
npm notice unpacked size: 23.9 MB
npm notice shasum:        6ceadcf29fe3d9915280ea1b204a67c157b20fc5
npm notice integrity:     sha512-KcRWYPhVRQJh0[...]bnKHmbMkqBWcQ==
npm notice total files:   123
npm notice
k3d-2.12.0.tgz

Fetching URL: https://registry.yarnpkg.com/k3d
> /opt/conda/bin/npm pack k3d@2.12.0
npm notice
npm notice 📦  k3d@2.12.0
npm notice === Tarball Contents ===
npm notice 761B   .eslintrc.js
npm notice 2.0kB  Gruntfile.js
npm notice 1.2kB  HOW-TO.md
npm notice 550B   README.md
npm notice 1.9kB  development_tf.html
npm notice 1.8kB  development.html
npm notice 3.6MB  dist/index.js
npm notice 1.7kB  dist/index.js.LICENSE.txt
npm notice 6.9MB  dist/index.js.map
npm notice 3.9MB  dist/standalone.js
npm notice 2.7kB  dist/standalone.js.LICENSE.txt
npm notice 8.9MB  dist/standalone.js.map
npm notice 2.0kB  package.json
npm notice 40.8kB src/core/Core.js
npm notice 609B   src/core/lib/cameraMode.js
npm notice 463B   src/core/lib/clippingPlanesGUIProvider.js
npm notice 5.5kB  src/core/lib/colorMapLegend.js
npm notice 3.0kB  src/core/lib/detachWindow.js
npm notice 1.4kB  src/core/lib/Error.js
npm notice 783B   src/core/lib/fullscreen.js
npm notice 4.7kB  src/core/lib/headless.html
npm notice 2.2kB  src/core/lib/helpers/buffer.js
npm notice 5.9kB  src/core/lib/helpers/colorMap.js
npm notice 119B   src/core/lib/helpers/detachedWindowHtml.js
npm notice 279B   src/core/lib/helpers/diff.js
npm notice 309B   src/core/lib/helpers/fileLoader.js
npm notice 162B   src/core/lib/helpers/float16Array.js
npm notice 19.7kB src/core/lib/helpers/marchingCubesLookupTables.js
npm notice 4.5kB  src/core/lib/helpers/marchingCubesPolygonise.js
npm notice 204B   src/core/lib/helpers/math.js
npm notice 1.1kB  src/core/lib/helpers/objectValidator.js
npm notice 5.6kB  src/core/lib/helpers/planeGUI.js
npm notice 3.4kB  src/core/lib/helpers/serialize.js
npm notice 10.7kB src/core/lib/helpers/voxelMeshGenerator.js
npm notice 420B   src/core/lib/helpers/yieldingLoop.js
npm notice 2.9kB  src/core/lib/Loader.js
npm notice 992B   src/core/lib/manipulate.js
npm notice 14.5kB src/core/lib/objectsGUIprovider.js
npm notice 290B   src/core/lib/resetCamera.js
npm notice 4.0kB  src/core/lib/screenshot.js
npm notice 1.6kB  src/core/lib/snapshot_inline.txt
npm notice 1.5kB  src/core/lib/snapshot_online.txt
npm notice 1.7kB  src/core/lib/snapshot_standalone.txt
npm notice 5.4kB  src/core/lib/snapshot.js
npm notice 9.0kB  src/core/lib/timeSeries.js
npm notice 706B   src/core/lib/viewMode.js
npm notice 290B   src/development.js
npm notice 218B   src/embed.js
npm notice 816B   src/extension.js
npm notice 212B   src/index.js
npm notice 1.4kB  src/k3d.css
npm notice 23.3kB src/k3d.js
npm notice 546B   src/labplugin.js
npm notice 748B   src/lodash.js
npm notice 8.9kB  src/providers/threejs/helpers/Fn.js
npm notice 1.9kB  src/providers/threejs/helpers/Intersection.js
npm notice 5.6kB  src/providers/threejs/helpers/SSAAChunkedRender.js
npm notice 6.2kB  src/providers/threejs/helpers/Streamline.js
npm notice 954B   src/providers/threejs/helpers/THREE.CopyShader.js
npm notice 16.6kB src/providers/threejs/helpers/THREE.MeshLine.js
npm notice 32.8kB src/providers/threejs/helpers/THREE.OrbitControls.js
npm notice 11.3kB src/providers/threejs/helpers/THREE.STLLoader.js
npm notice 24.0kB src/providers/threejs/helpers/THREE.TrackballControls.js
npm notice 58.7kB src/providers/threejs/helpers/TransformControls.js
npm notice 10.9kB src/providers/threejs/helpers/Voxels.js
npm notice 7.4kB  src/providers/threejs/initializers/Camera.js
npm notice 6.2kB  src/providers/threejs/initializers/Canvas.js
npm notice 3.3kB  src/providers/threejs/initializers/Manipulate.js
npm notice 10.2kB src/providers/threejs/initializers/Renderer.js
npm notice 25.5kB src/providers/threejs/initializers/Scene.js
npm notice 486B   src/providers/threejs/initializers/Setup.js
npm notice 1.0kB  src/providers/threejs/interactions/intersectCallback.js
npm notice 7.6kB  src/providers/threejs/interactions/Voxels.js
npm notice 10.2kB src/providers/threejs/objects/Label.js
npm notice 1.3kB  src/providers/threejs/objects/Line.js
npm notice 2.8kB  src/providers/threejs/objects/LineMesh.js
npm notice 3.9kB  src/providers/threejs/objects/LineSimple.js
npm notice 5.6kB  src/providers/threejs/objects/LineThick.js
npm notice 7.1kB  src/providers/threejs/objects/MarchingCubes.js
npm notice 1.2kB  src/providers/threejs/objects/Mesh.js
npm notice 8.9kB  src/providers/threejs/objects/MeshStandard.js
npm notice 6.8kB  src/providers/threejs/objects/MeshVolume.js
npm notice 7.2kB  src/providers/threejs/objects/MIP.js
npm notice 1.3kB  src/providers/threejs/objects/Points.js
npm notice 9.1kB  src/providers/threejs/objects/PointsBillboard.js
npm notice 8.0kB  src/providers/threejs/objects/PointsMesh.js
npm notice 911B   src/providers/threejs/objects/shaders/MeshVolume.fragment.glsl
npm notice 394B   src/providers/threejs/objects/shaders/MeshVolume.vertex.glsl
npm notice 5.2kB  src/providers/threejs/objects/shaders/MIP.fragment.glsl
npm notice 788B   src/providers/threejs/objects/shaders/MIP.vertex.glsl
npm notice 1.8kB  src/providers/threejs/objects/shaders/Points.3d.fragment.glsl
npm notice 334B   src/providers/threejs/objects/shaders/Points.dot.fragment.glsl
npm notice 1.2kB  src/providers/threejs/objects/shaders/Points.dot.vertex.glsl
npm notice 520B   src/providers/threejs/objects/shaders/Points.flat.fragment.glsl
npm notice 1.3kB  src/providers/threejs/objects/shaders/Points.vertex.glsl
npm notice 2.3kB  src/providers/threejs/objects/shaders/PointsMesh.fragment.glsl
npm notice 1.8kB  src/providers/threejs/objects/shaders/PointsMesh.vertex.glsl
npm notice 549B   src/providers/threejs/objects/shaders/Texture.fragment.glsl
npm notice 304B   src/providers/threejs/objects/shaders/Texture.vertex.glsl
npm notice 9.6kB  src/providers/threejs/objects/shaders/Volume.fragment.glsl
npm notice 5.0kB  src/providers/threejs/objects/shaders/Volume.lightmap.fragment.glsl
npm notice 134B   src/providers/threejs/objects/shaders/Volume.lightmap.vertex.glsl
npm notice 788B   src/providers/threejs/objects/shaders/Volume.vertex.glsl
npm notice 2.8kB  src/providers/threejs/objects/SparseVoxels.js
npm notice 2.8kB  src/providers/threejs/objects/STL.js
npm notice 4.1kB  src/providers/threejs/objects/Surface.js
npm notice 5.5kB  src/providers/threejs/objects/Text.js
npm notice 4.6kB  src/providers/threejs/objects/Text2d.js
npm notice 887B   src/providers/threejs/objects/Texture.js
npm notice 6.8kB  src/providers/threejs/objects/TextureData.js
npm notice 3.3kB  src/providers/threejs/objects/TextureImage.js
npm notice 4.6kB  src/providers/threejs/objects/TextureText.js
npm notice 2.0kB  src/providers/threejs/objects/TorusKnot.js
npm notice 6.2kB  src/providers/threejs/objects/VectorField.js
npm notice 6.0kB  src/providers/threejs/objects/Vectors.js
npm notice 15.4kB src/providers/threejs/objects/Volume.js
npm notice 1.0kB  src/providers/threejs/objects/Voxels.js
npm notice 8.3kB  src/providers/threejs/objects/VoxelsGroup.js
npm notice 2.7kB  src/providers/threejs/provider.js
npm notice 2.1kB  src/standalone.js
npm notice 18.9kB src/transferFunctionEditor.js
npm notice 146B   src/version.js
npm notice 4.7kB  webpack.config.js
npm notice === Tarball Details ===
npm notice name:          k3d
npm notice version:       2.12.0
npm notice filename:      k3d-2.12.0.tgz
npm notice package size:  6.9 MB
npm notice unpacked size: 23.9 MB
npm notice shasum:        6ceadcf29fe3d9915280ea1b204a67c157b20fc5
npm notice integrity:     sha512-KcRWYPhVRQJh0[...]bnKHmbMkqBWcQ==
npm notice total files:   123
npm notice
k3d-2.12.0.tgz

Node v17.8.0

Yarn configuration loaded.
Building jupyterlab assets (production, minimized)
> node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js install --non-interactive
yarn install v1.21.1
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
warning requirejs@2.3.6: Invalid bin entry for "r.js" (in "requirejs").
info fsevents@2.3.2: The platform "linux" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@jupyterlab/extensionmanager > react-paginate@6.5.0" has incorrect peer dependency "react@^16.0.0".
warning "@jupyterlab/json-extension > react-highlighter@0.4.3" has incorrect peer dependency "react@^0.14.0 || ^15.0.0 || ^16.0.0".
warning "@jupyterlab/json-extension > react-json-tree@0.15.0" has unmet peer dependency "@types/react@^16.3.0 || ^17.0.0".
warning "@jupyterlab/vdom > @nteract/transform-vdom@4.0.16-alpha.0" has incorrect peer dependency "react@^16.3.2".
warning " > @lumino/coreutils@1.8.0" has unmet peer dependency "crypto@1.0.1".
warning "@jupyterlab/builder > @jupyterlab/buildutils > verdaccio > clipanion@3.0.0-rc.12" has unmet peer dependency "typanion@*".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[5/5] Building fresh packages...
success Saved lockfile.
Done in 8.34s.

> node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer --fail
yarn run v1.21.1
$ /opt/conda/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer --fail
Done in 0.44s.

> node /opt/conda/lib/python3.8/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.21.1
$ webpack --config webpack.prod.minimize.config.js
[webpack-cli] ModuleNotFoundError: Module not found: Error: Can't resolve 'k3d/dist/labplugin' in '/opt/conda/share/jupyter/lab/staging/build'
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/Compilation.js:1768:28
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:742:13
    at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:10:1)
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:276:22
    at eval (eval at create (/opt/conda/share/jupyter/lab/staging/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:405:22
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:119:11
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:650:24
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:813:8
    at /opt/conda/share/jupyter/lab/staging/node_modules/webpack/lib/NormalModuleFactory.js:933:5
resolve 'k3d/dist/labplugin' in '/opt/conda/share/jupyter/lab/staging/build'
  Parsed request is a module
  using description file: /opt/conda/share/jupyter/lab/staging/build/package.json (relative path: .)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /opt/conda/share/jupyter/lab/staging/build/node_modules doesn't exist or is not a directory
      looking for modules in /opt/conda/share/jupyter/lab/staging/node_modules
        existing directory /opt/conda/share/jupyter/lab/staging/node_modules/k3d
          using description file: /opt/conda/share/jupyter/lab/staging/node_modules/k3d/package.json (relative path: .)
            using description file: /opt/conda/share/jupyter/lab/staging/node_modules/k3d/package.json (relative path: ./dist/labplugin)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /opt/conda/share/jupyter/lab/staging/node_modules/k3d/dist/labplugin doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /opt/conda/share/jupyter/lab/staging/node_modules/k3d/dist/labplugin.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /opt/conda/share/jupyter/lab/staging/node_modules/k3d/dist/labplugin.json doesn't exist
              .wasm
                Field 'browser' doesn't contain a valid alias configuration
                /opt/conda/share/jupyter/lab/staging/node_modules/k3d/dist/labplugin.wasm doesn't exist
              as directory
                /opt/conda/share/jupyter/lab/staging/node_modules/k3d/dist/labplugin doesn't exist
      /opt/conda/share/jupyter/lab/node_modules doesn't exist or is not a directory
      /opt/conda/share/jupyter/node_modules doesn't exist or is not a directory
      /opt/conda/share/node_modules doesn't exist or is not a directory
      /opt/conda/node_modules doesn't exist or is not a directory
      /opt/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/opt/conda/lib/python3.8/site-packages/jupyterlab/debuglog.py", line 48, in debug_logging
    yield

  File "/opt/conda/lib/python3.8/site-packages/jupyterlab/labextensions.py", line 140, in start
    build(clean_staging=self.should_clean,

  File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 482, in build
    return handler.build(name=name, version=version, static_url=static_url,

  File "/opt/conda/lib/python3.8/site-packages/jupyterlab/commands.py", line 695, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: lab
```

**Comment by artur-trzesiok** [comment]
Do you try to build k3d from source or that is happened during installation from pip/conda?

**Comment by agoose77** [comment]
@Anmol-Sharma you shouldn't use `jupyter labextension install` with new (3.x) versions of JupyterLab (unless you happen to be installing a 3.x extension, and you _need_ to install it from source). Installing it with `pip/conda` is the preferred method, as it keeps the extension in sync with the Python package, and doesn't require NodeJS.

**Comment by Anmol-Sharma** [comment]
@agoose77 thanks for the help. I completely removed jupyterlab and did a clean reinstall of k3d as well without the extra step of installing the extension. Now it works without any issue.

Since the additional step of installing the extension was part of the original readme, I thought it would be a necessary step, but now it turns out it isn't. So thanks for your help.
