### ISSUE TITLE
How could one integrate k3d with pyviz panels?

### ISSUE THREAD

**Issue by ea42gh** [K3D-tools/K3D-jupyter#447]
### Description

[panel](https://panel.holoviz.org/) used to have a pane that would display k3d plots.
That pane is no longer available due to code refactoring.

I suspect using one of the current panes might work easily,
but do not know how to integrate the two?

**Comment by ichko** [comment]
Hey, I also stumbled upon this issue.

Minimal code example to reproduce in a notebook environment:
```py
import k3d
plot = k3d.Plot()
plot += k3d.points([0, 0, 0])

pn.Column("a", pn.panel(plot), "b")
```
and the generated plot is empty.

Going to the console you get this error message:
```log
TypeError: world.cleanup is not a function
    at K3D.disable (Core.js:1217:1)
    at refresh (Canvas.js:211:1)
    at module.exports (Canvas.js:281:1)
    at new K3D (Core.js:1234:1)
    at PlotView._init (k3d.js:323:1)
    at f (backbone.js:335:57)
    at g (backbone.js:322:19)
    at d (backbone.js:110:16)
    at a.trigger (backbone.js:312:5)
    at r.render (panel.min.js:120:1118)
```

and this comes from a part of the code responsible for k3d teardown... maybe..
<img width="426" alt="image" src="https://github.com/K3D-tools/K3D-jupyter/assets/7668305/23ca51d9-cb74-4db0-9866-b8888a4ab40d">

going up a stack frame:

<img width="413" alt="image" src="https://github.com/K3D-tools/K3D-jupyter/assets/7668305/59464df3-acc0-4c22-b5d4-1b156e952aa9">

It is interesting that the error occurs whilst teardown, which I suppose is not what we want while trying to show a plot.

There is also an unresolved discussion about this in the holoviz forum - https://discourse.holoviz.org/t/panel-meets-k3d-jupyter/1604/17  

I would love to be able to show a k3d plot in a panel application.

**Comment by artur-trzesiok** [comment]
@ea42gh @ichko — the crash is fixed on `devel`, and it turned out not to be a teardown bug at all, despite what the stack trace suggests. Thank you @ichko for posting it; it pointed straight at the cause.

**What was happening.** The Canvas initializer ends by calling `refresh()` synchronously, so the render loop starts while `new K3D(...)` is still running. Inside `refresh` there was a guard that tears the instance down when its target node is not in the document — meant to catch a notebook output that goes away. During construction that condition is also true for any host that builds its subtree detached and inserts it later, which is exactly what Panel does: your trace shows `panel.min.js → backbone trigger → PlotView._init` firing `displayed` while the node is still detached. In Jupyter the same event arrives after insertion, which is why it never showed there.

Teardown then ran against a half-built world. `world.cleanup` is defined by the *Scene* initializer, which runs after *Canvas*, hence `TypeError: world.cleanup is not a function`. By then `disabling` was already set, so every later frame returned immediately and the plot stayed blank — and the TypeError hid the real cause, which is why this looked like a teardown problem.

**The fix.** A node now has to have been attached before its disappearance counts as going away, and `disable()` no longer assumes a fully built world. Construction against a detached node is a legitimate pattern, not an error.

Two things worth knowing beyond the crash:

- A detached node measures 0×0, and that used to propagate into a zero camera aspect and a   zero-sized canvas. That is also fixed on `devel` (#486): a zero measurement is now treated as   "not laid out yet", and the real size is applied by the resize observer once the node is
  inserted. Without that, fixing this crash alone would have left you with a blank plot anyway.
- For a **deployed** Panel app (`panel serve`, outside Jupyter) there is a second requirement  that no code change can substitute for: `ipywidgets_bokeh` resolves widget modules from a CDN   by module name and version, so the `k3d` npm package has to be published for the exact version   you run. Inside a notebook this does not apply, since the Jupyter extension supplies the
  frontend.

**On the original question** — no dedicated pane is needed. `pn.panel(plot)` works because Panel recognises an ipywidget; K3D uses no kernel API of its own and leaves all of that to ipywidgets.

Both of these land in 2.18.0. If either of you can try it against Panel once released, that would be genuinely useful: the tests here cover construction against a detached node and the recovery once it is inserted, but nothing in our suite exercises Panel itself.
