### ISSUE TITLE
 UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 76: ordinal not in range(128)

### ISSUE THREAD

**Issue by korniichuk** [K3D-tools/K3D-jupyter#6]
Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-35wbg1lf-build/setup.py", line 14, in <module>
        k3d_version = get_version('**k3d_widget/lib/k3d/bower.json**')
      File "/tmp/pip-35wbg1lf-build/setup.py", line 10, in get_version
        return json.load(bower)['version']
      File "/opt/conda/lib/python3.4/json/__init__.py", line 265, in load
        return loads(fp.read(),
      File "/opt/conda/lib/python3.4/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 76: ordinal not in range(128)**

Fix special Polish characters here too:
    - ``K3D-tools/K3D/bower.json``,
    - ``K3D-tools/K3D/package.json``,
    - ``K3D-tools/K3D-shim/bower.json``,
    - ``K3D-tools/K3D-shim/package.json``.

**Comment by artur-trzesiok** [comment]
Thanks. All polish characters was removed.
